[project]
# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g., LangChain cache)
cache = false

# Whether to persist user environment variables (API keys) to the database
persist_user_env = false

# Whether to mask user environment variables (API keys) in the UI with password type
mask_user_env = false

# Authorized origins for the Chainlit UI (keep localhost for debugging)
allow_origins = ["https://app.authservices.cloud", "https://api.authservices.cloud", "http://127.0.0.1:8001", "http://localhost:8001"]

# --- merged metadata you added ---
name = "Bio-RAG"
description = "RAG UI for OpenSearch + reranker + Gemini"
max_steps = 200

# If your backend enforces CORS, these are the frontend origins that will call it
# (kept here for reference; API CORS is typically configured in FastAPI code)
cors_origins = ["https://app.authservices.cloud", "https://api.authservices.cloud"]

[features]
# Display/rendering features
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = false

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
enabled = true
# Be strict in prod if you want: e.g. ["image/*","application/pdf"]
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
enabled = false
sample_rate = 24000

[features.mcp]
enabled = false

[features.mcp.sse]
enabled = true

[features.mcp.streamable-http]
enabled = true

[features.mcp.stdio]
enabled = true
# Only the executables in the allow list can be used for MCP stdio server.
allowed_executables = ["npx", "uvx"]

[UI]
# Branding
name = "Bio-RAG Chat"

# CoT display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# The style of alert boxes. Can be "classic" or "modern".
alert_style = "classic"

# Optional assets (leave blank if not used)
logo_file_url = ""
default_avatar_file_url = ""
# custom_css = "/public/custom.css"
# custom_js  = "/public/custom.js"

[meta]
generated_by = "2.8.0"